@TOKEN=eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.bQTnz6AuMJvmXXQsVPrxeQNvzDkimo7VNXxHeSBfClLufmCVZRUuyTwJF311JHuh
### Users
GET https://gestpatrimonioserver.onrender.com/users

### REGISTER
POST https://gestpatrimonioserver.onrender.com/users
content-type: application/json

{
  "name": "test",
  "email": "admin",
  "role": "admin"
}

### LOGIN
PUT https://gestpatrimonioserver.onrender.com/users/1
content-type: application/json

{
  "name": "user",
  "email": "user",
  "role": "user"
}

### GET Users
GET https://gestpatrimonioserver.onrender.com/users/1

### DELETE Users
DELETE https://gestpatrimonioserver.onrender.com/users/1
