@TOKEN=eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.bQTnz6AuMJvmXXQsVPrxeQNvzDkimo7VNXxHeSBfClLufmCVZRUuyTwJF311JHuh
### Users
GET http://localhost:8081/users

### REGISTER
POST http://localhost:8081/users
content-type: application/json

{
  "name": "test",
  "email": "admin",
  "role": "admin"
}

### LOGIN
PUT http://localhost:8081/users/1
content-type: application/json

{
  "name": "user",
  "email": "user",
  "role": "user"
}

### GET Users
GET http://localhost:8081/users/1

### DELETE Users
DELETE http://localhost:8081/users/1
